name: Test basic functionality on multiple platforms

on:
  push:
    branches: [ "experimental_mac_support" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v3

    - name: Install_Deps
      run: pip install pydub
    
    - name: Test
      run: cd python/test ; python3 verify_marvin.py
